import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'
import './styles.css'

type Tab='ops'|'pim'|'counsellor'|'students'
type Course={course_id:string;canonical_title:string;provider_name:string;country_code:string;level_code:string|null;course_url:string|null;provider_website:string|null;completeness_score:number;completeness_score_v2:number|null;has_registration:boolean;has_structure:boolean;has_fee:boolean;has_intake:boolean;has_english:boolean;has_description:boolean;has_linked_scholarship?:boolean;scholarship_count?:number;fee_amount?:number|null;fee_currency?:string|null;ielts_overall?:number|null;duration_weeks?:number|null}
type Job={id:string;layer:number|null;job_kind:string;status:string;counters:Record<string,number>;started_at:string|null;completed_at:string|null;created_at:string}
type Change={id:number;entity_type:string;action:string;changed_fields:any;created_at:string}
type Review={id:string;entity_type:string|null;reason:string;review_type:string|null;priority:number;status:string;created_at:string}
type Country={country_code:string;name:string}
type Scholarship={id:string;canonical_name:string;provider_name:string;academic_year:number|null;value_percent_max:number|null;value_amount_max:number|null;currency:string|null;application_mode:string|null;status:string|null}
type FieldValue={id:string;entity_type:string;field_code:string;value_text:string|null;value_number:number|null;value_code:string|null;source_layer:number|null;confidence:number|null;review_status:string|null;is_preferred:boolean|null}

const LAYERS=[
 {n:1,title:'Regulatory / canonical',tag:'Registers',desc:'Loads trusted provider and course identity from official regulatory sources.'},
 {n:2,title:'Discovery + evidence',tag:'Official pages',desc:'Discovers official university pages, captures immutable evidence and deterministic facts.'},
 {n:3,title:'AI enrichment',tag:'Confidence routed',desc:'Normalises complex fields and routes uncertain values to human review.'},
 {n:4,title:'Human curation',tag:'Review queue',desc:'Curators approve, correct, map or reject uncertain values with an audit trail.'},
]

export default function App(){
 const[tab,setTab]=useState<Tab>('ops');const[stats,setStats]=useState<any>(null);const[countries,setCountries]=useState<Country[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[changes,setChanges]=useState<Change[]>([]);const[reviews,setReviews]=useState<Review[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[courseTotal,setCourseTotal]=useState(0);const[coursePage,setCoursePage]=useState(0);const[country,setCountry]=useState('all');const[query,setQuery]=useState('');const[scholarships,setScholarships]=useState<Scholarship[]>([]);const[fields,setFields]=useState<FieldValue[]>([]);const[selected,setSelected]=useState<Set<string>>(new Set());const[loading,setLoading]=useState(true)
 async function refresh(){setLoading(true);const[a,b,c,d,e,f,g]=await Promise.all([
  supabase.from('catalogue_stats').select('*').single(),supabase.from('ref_countries').select('country_code,name').order('country_code'),supabase.from('ingest_jobs').select('*').order('created_at',{ascending:false}).limit(40),supabase.from('ingest_change_log').select('id,entity_type,action,changed_fields,created_at').order('created_at',{ascending:false}).limit(80),supabase.from('review_queue').select('id,entity_type,reason,review_type,priority,status,created_at').order('created_at',{ascending:false}).limit(50),supabase.from('scholarship_catalogue_v2').select('*').order('provider_name').order('canonical_name').limit(100),supabase.from('field_values').select('id,entity_type,field_code,value_text,value_number,value_code,source_layer,confidence,review_status,is_preferred').order('created_at',{ascending:false}).limit(50)
 ]);setStats(a.data);setCountries((b.data as Country[])??[]);setJobs((c.data as Job[])??[]);setChanges((d.data as Change[])??[]);setReviews((e.data as Review[])??[]);setScholarships((f.data as Scholarship[])??[]);setFields((g.data as FieldValue[])??[]);setLoading(false)}
 useEffect(()=>{refresh()},[])
 useEffect(()=>{loadCourses()},[coursePage,country,query])
 async function loadCourses(){let q=supabase.from('course_completeness_v2').select('*',{count:'exact'}).order('country_code').order('provider_name').order('canonical_title').range(coursePage*50,coursePage*50+49);if(country!=='all')q=q.eq('country_code',country);if(query.trim())q=q.ilike('canonical_title',`%${query.trim()}%`);const{data,count}=await q;setCourses((data as Course[])??[]);setCourseTotal(count??0)}
 function toggle(id:string){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 const openReviews=reviews.filter(r=>r.status==='open');
 return <div className="app"><header className="hero"><div className="hero-row"><div><div className="eyebrow">COURSEFINDER DATA PLATFORM</div><h1>4-Layer Data Pipeline</h1><p>Read-only demonstration of catalogue, provenance, completeness, scholarships and PIM enrichment.</p></div><button className="ghost" onClick={refresh}>↻ Refresh</button></div><div className="stats"><Stat label="Countries" value={loading?'…':stats?.countries??0}/><Stat label="Providers" value={loading?'…':stats?.providers??0}/><Stat label="Courses" value={loading?'…':Number(stats?.courses??0).toLocaleString()}/><Stat label="Avg completeness" value={loading?'…':`${stats?.avg_completeness??0}%`} accent/></div><nav>{[['ops','Pipeline ops'],['pim','PIM model'],['counsellor','Counsellor view'],['students','Student finder']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as Tab)}>{v}</button>)}</nav></header>
 {tab==='ops'&&<main><Section title="Pipeline execution model"><div className="layers">{LAYERS.map(l=><article className={`layer l${l.n}`} key={l.n}><div className="layer-head"><span>Layer {l.n}</span><b>{l.tag}</b></div><h3>{l.title}</h3><p>{l.desc}</p><div className="status"><span>Demo status</span><em>read only</em>{l.n===4?<small>{openReviews.length} open review item(s)</small>:<LatestJob layer={l.n} jobs={jobs}/>}</div></article>)}</div></Section><Section title="Security boundary"><div className="security"><Info title="Secrets" text="Scraper, LLM and service-role secrets stay server-side in Supabase Edge Function secrets."/><Info title="Demo access" text="Publishable key only. No pipeline execution, canonical writes, reset or embedding spend."/><Info title="Operational control" text="Layer execution and private evidence stay in the authenticated PIM admin."/></div></Section><Section title="Course catalogue & V2 completeness"><CourseTable courses={courses} total={courseTotal} page={coursePage} setPage={setCoursePage} countries={countries} country={country} setCountry={setCountry} query={query} setQuery={setQuery} selected={selected} toggle={toggle}/></Section><Section title="Layer 4 — Human curation"><ReviewSummary rows={reviews}/></Section><Section title="Jobs, change history & evidence posture"><Logs jobs={jobs} changes={changes}/></Section></main>}
 {tab==='pim'&&<main><Section title="UnoPIM-inspired model"><div className="pim-grid"><div className="families">{[['Course','General · Admissions · Fees · Intakes · English · Scholarships · Delivery'],['Scholarship','General · Award Value · Eligibility · Merit · Geography · Application · Evidence'],['Provider','General · Regulatory · Contact · Delivery'],['Student Profile','Identity · Academic · English · Study Intent']].map(([a,b])=><Info key={a} title={a} text={b}/>)}</div><div><h3>Live custom / enriched values</h3><FieldTable rows={fields}/></div></div></Section><Section title="Scholarship catalogue"><ScholarshipTable rows={scholarships}/></Section></main>}
 {tab==='counsellor'&&<main><Section title="Counsellor workbench"><CourseTable courses={courses} total={courseTotal} page={coursePage} setPage={setCoursePage} countries={countries} country={country} setCountry={setCountry} query={query} setQuery={setQuery} selected={selected} toggle={toggle}/>{selected.size>0&&<div className="shortlist">{selected.size} course(s) shortlisted for comparison. <button onClick={()=>setSelected(new Set())}>clear</button></div>}</Section><Section title="Shortlist"><div className="empty">Select courses above to build a counsellor shortlist. PDF export remains part of the internal V5.8 workflow.</div></Section></main>}
 {tab==='students'&&<main><Section title="Student course finder"><StudentFinder/></Section></main>}
 <footer>Public demo: read-only Supabase catalogue surfaces · Layer execution, secrets, private evidence and canonical writes remain in the authenticated PIM admin.</footer></div>
}

function Stat({label,value,accent}:{label:string;value:any;accent?:boolean}){return <div className="stat"><span>{label}</span><strong className={accent?'accent':''}>{value}</strong></div>}
function Section({title,children}:{title:string;children:any}){return <section><h2>{title}</h2>{children}</section>}
function Info({title,text}:{title:string;text:string}){return <div className="info"><strong>{title}</strong><p>{text}</p><span className="chip">read only</span></div>}
function LatestJob({layer,jobs}:{layer:number;jobs:Job[]}){const j=jobs.find(x=>x.layer===layer);return j?<><small>{j.status} · {j.job_kind}</small><small>{new Date(j.created_at).toLocaleString()}</small></>:<small>No tracked Layer {layer} job yet.</small>}
function CourseTable(p:any){const pages=Math.max(1,Math.ceil(p.total/50));return <div className="panel"><div className="toolbar"><input placeholder="Search course title…" value={p.query} onChange={(e:any)=>{p.setPage(0);p.setQuery(e.target.value)}}/><select value={p.country} onChange={(e:any)=>{p.setPage(0);p.setCountry(e.target.value)}}><option value="all">All countries</option>{p.countries.map((c:Country)=><option key={c.country_code} value={c.country_code}>{c.name} ({c.country_code})</option>)}</select><span>{p.total.toLocaleString()} courses</span></div><div className="table-wrap"><table><thead><tr><th></th><th>Course</th><th>Provider</th><th>Country</th><th>Reg.</th><th>Fee</th><th>Intake</th><th>English</th><th>Scholarship</th><th>Complete</th></tr></thead><tbody>{p.courses.map((c:Course)=><tr key={c.course_id}><td><input type="checkbox" checked={p.selected.has(c.course_id)} onChange={()=>p.toggle(c.course_id)}/></td><td><b>{c.canonical_title}</b><small>{c.level_code??''}</small></td><td>{c.provider_name}</td><td>{c.country_code}</td><td>{mark(c.has_registration)}</td><td>{mark(c.has_fee)}</td><td>{mark(c.has_intake)}</td><td>{mark(c.has_english)}</td><td>{c.scholarship_count?`${c.scholarship_count} linked`:mark(!!c.has_linked_scholarship)}</td><td><Progress value={Number(c.completeness_score_v2??c.completeness_score??0)}/></td></tr>)}</tbody></table></div><div className="pager"><span>Page {p.page+1} of {pages}</span><div><button disabled={p.page===0} onClick={()=>p.setPage((x:number)=>x-1)}>Prev</button><button disabled={p.page>=pages-1} onClick={()=>p.setPage((x:number)=>x+1)}>Next</button></div></div></div>}
const mark=(x:boolean)=><span className={x?'yes':'no'}>{x?'✓':'×'}</span>
function Progress({value}:{value:number}){const v=Math.round(value);return <div className="progress"><i style={{width:`${v}%`}}/><span>{v}%</span></div>}
function ReviewSummary({rows}:{rows:Review[]}){const open=rows.filter(r=>r.status==='open');return <div className="panel review-list">{open.slice(0,10).map(r=><div key={r.id}><div><b>{r.review_type??r.reason}</b><small>{r.entity_type??'entity'} · priority {r.priority}</small></div><span className="chip amber">open</span></div>)}{!open.length&&<div className="empty">No open review items.</div>}<p className="muted">Review details and actions are intentionally hidden from the public demo.</p></div>}
function Logs({jobs,changes}:{jobs:Job[];changes:Change[]}){return <div className="logs"><div className="panel"><h3>Recent jobs</h3>{jobs.slice(0,12).map(j=><div className="logrow" key={j.id}><span className={`layer-pill l${j.layer??0}`}>{j.layer?`L${j.layer}`:'—'}</span><b>{j.job_kind}</b><span>{j.status}</span><small>{new Date(j.created_at).toLocaleString()}</small></div>)}</div><div className="panel"><h3>Recent changes</h3>{changes.slice(0,12).map(c=><div className="logrow" key={c.id}><b>{c.entity_type}</b><span>{c.action}</span><small>{new Date(c.created_at).toLocaleString()}</small></div>)}</div><div className="panel evidence"><h3>Evidence</h3><p>Raw HTML, screenshots, PDFs and extracted JSON are retained in private Supabase Storage.</p><p>New evidence versions supersede older artefacts rather than overwriting history.</p><p>Layer-4 curators access objects through short-lived signed URLs.</p></div></div>}
function ScholarshipTable({rows}:{rows:Scholarship[]}){return <div className="panel table-wrap"><table><thead><tr><th>Scholarship</th><th>Provider</th><th>Year</th><th>Award</th><th>Application</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.canonical_name}</b></td><td>{r.provider_name}</td><td>{r.academic_year??'—'}</td><td>{r.value_percent_max?`${r.value_percent_max}%`:r.value_amount_max?`${r.currency??''} ${Number(r.value_amount_max).toLocaleString()}`:'—'}</td><td>{r.application_mode??'—'}</td><td><span className="chip">{r.status??'active'}</span></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No scholarship records available to the public demo surface.</div>}</div>}
function FieldTable({rows}:{rows:FieldValue[]}){return <div className="panel table-wrap"><table><thead><tr><th>Entity</th><th>Attribute</th><th>Value</th><th>Layer</th><th>Confidence</th><th>State</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td>{v.entity_type}</td><td><code>{v.field_code}</code></td><td>{v.value_text??v.value_code??v.value_number??'—'}</td><td>{v.source_layer?`L${v.source_layer}`:'—'}</td><td>{v.confidence==null?'—':`${Math.round(Number(v.confidence)*100)}%`}</td><td><span className="chip">{v.is_preferred?'preferred':v.review_status??'observed'}</span></td></tr>)}</tbody></table></div>}
function StudentFinder(){const[q,setQ]=useState('');const[rows,setRows]=useState<Course[]>([]);const[busy,setBusy]=useState(false);async function run(text?:string){const x=(text??q).trim();if(!x)return;if(text)setQ(text);setBusy(true);const{data}=await supabase.from('course_completeness_v2').select('*').ilike('canonical_title',`%${x}%`).order('completeness_score_v2',{ascending:false}).limit(20);setRows((data as Course[])??[]);setBusy(false)}return <div className="panel student"><div className="searchbox"><input placeholder="What would you like to study?" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()}/><button onClick={()=>run()}>{busy?'Searching…':'Search'}</button></div><div className="suggestions">{['computer science','MBA','nursing','data science','engineering'].map(x=><button key={x} onClick={()=>run(x)}>{x}</button>)}</div>{rows.map(c=><div className="result" key={c.course_id}><div><b>{c.canonical_title}</b><small>{c.provider_name} · {c.country_code} · {c.level_code??''}</small></div><div><span className="chip">{Math.round(Number(c.completeness_score_v2??c.completeness_score??0))}% complete</span>{c.fee_amount&&<span>{c.fee_currency} {Number(c.fee_amount).toLocaleString()}</span>}{c.ielts_overall&&<span>IELTS {c.ielts_overall}</span>}{c.course_url&&<a href={c.course_url} target="_blank" rel="noreferrer">Course page ↗</a>}</div></div>)}</div>}
